// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxzcezracqyrbnixlycg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4emNlenJhY3F5cmJuaXhseWNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQwNTI3OTEsImV4cCI6MjA4OTYyODc5MX0.XTS4CWLEP0-5D13KmjFNTqxSH5CyrQMwopBvXbkd1RM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
